### Matrix Operation

In [1]:
import math
import numpy as np

In [3]:
matrixA = np.array([[2, -1], [0, 3]])
matrixB = np.array([[1, 2], [-3, 4]])
print("Matrix A:")
print(matrixA)
print(matrixA.shape)
print("Matrix B:")
print(matrixB)
print(matrixB.shape)

matrixC = matrixA + matrixB
print("Matrix C (A + B):")
print(matrixC)
print(matrixC.shape)

matrixD = matrixA @ matrixB
print("Matrix D (A * B):")
print(matrixD)
print(matrixD.shape)

matrixE = 3*matrixA - 2*matrixB
print("Matrix E (3A - 2B):")
print(matrixE)
print(matrixE.shape)

Matrix A:
[[ 2 -1]
 [ 0  3]]
(2, 2)
Matrix B:
[[ 1  2]
 [-3  4]]
(2, 2)
Matrix C (A + B):
[[ 3  1]
 [-3  7]]
(2, 2)
Matrix D (A * B):
[[ 5  0]
 [-9 12]]
(2, 2)
Matrix E (3A - 2B):
[[ 4 -7]
 [ 6  1]]
(2, 2)


##  Determinants and Inverses  

In [4]:
det = np.linalg.det(matrixA)
print("Determinant of A:")
print(det)

if det != 0:
    matrixF = matrixA - 1
    print("Matrix F (A - 1):")
    print(matrixF)

Determinant of A:
6.0
Matrix F (A - 1):
[[ 1 -2]
 [-1  2]]


## Eigen Values and Eigen Vectors

In [5]:
matrixC = np.array([[4, 1], [-2, 1]])
print("Matrix C:")
print(matrixC)
print(matrixC.shape)

matrixD = np.linalg.eigh(matrixC)
print("Eigenvalues and Eigenvectors of C:")
print(matrixD)

Matrix C:
[[ 4  1]
 [-2  1]]
(2, 2)
Eigenvalues and Eigenvectors of C:
EighResult(eigenvalues=array([0., 5.]), eigenvectors=array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]]))


In [2]:
X = np.array([[4, 1.5, 100], [6, 2.0, 150]])
Y = np.array([20, 30])

beta = np.linalg.pinv(X.T @ X) @ X.T @ Y

print("β =", beta)

car3= np.array([[8, 3.0, 200]])

price_car3 = car3 @ beta

print(f" price of car 3 : {price_car3[0]}")

β = [7.98722045e-03 4.54747351e-13 1.99680511e-01]
 price of car 3 : 40.000000000000696
